DROP DATABASE IF EXISTS database1;
CREATE DATABASE database1;
USE database1;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
username VARCHAR(30) NOT NULL,
password VARCHAR(65) NOT NULL,
email VARCHAR(30) NOT NULL,
active INT(1) NOT NULL DEFAULT 0,
regdate TIMESTAMP
);

DROP TABLE IF EXISTS items;
CREATE TABLE items (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
menu VARCHAR(30) NOT NULL,
item VARCHAR(30) NOT NULL,
image VARCHAR(30) NOT NULL,
price VARCHAR(30) NOT NULL,
regdate TIMESTAMP
);

DROP TABLE IF EXISTS basket;
CREATE TABLE basket (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
iditem INT(6) UNSIGNED NOT NULL,
Iduser INT(6) UNSIGNED NOT NULL,
regdate TIMESTAMP
);


DROP TABLE IF EXISTS login;
CREATE TABLE login (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS msgs;
CREATE TABLE msgs (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL,
msg VARCHAR(256) NOT NULL,
pict VARCHAR(256) NOT NULL,
timestamp TIMESTAMP
);




